openapi: 3.0.0
info:
  version: 0.0.8
  title: Test Harness
  description: >-
    The Test Harness is a tool to enable testing of the Mercury
    project by exposing rest endpoints that will act as the middleman between
    test tools and mercury project.
servers:
  - url: http://localhost:8082/test-harness
    description: local
  - url: https://test-harness.dev.mercury.sitacloud.aero/test-harness
    description: dev
paths:
  /api/v1/ibm/send:
    $ref: paths/ibm/send/ibm-send-one-message.yaml
  /api/v1/ibm/send/multiple-messages:
    $ref: paths/ibm/send/ibm-send-multiple-messages.yaml
  /api/v1/ibm/receive:
    $ref: paths/ibm/receive/ibm-receive.yaml
  /api/v1/ibm/load/generate:
    $ref: paths/ibm/load/generate/ibm-load-generate.yaml
  /api/v1/ibm/load/inject/{id}:
    $ref: paths/ibm/load/inject/ibm-load-inject.yaml
  /api/v2/messages/inject:
    post:
      tags:
        - Messages
      description: >
        This endpoint allows for injection of data into the mercury system. It currently operates with IBM MQ and is 
        used to send messages to specified destinations. It can be used to inject a pre-generated load.
      summary: "POST messages/v2/inject"
      operationId: "inject"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SendMessageIbmMqRequestDto"
            examples:
              OneServerOneDestinationNames:
                $ref: "components/messages/inject/request/examples/OneServerOneDestinationNames.yaml"
              DevOneServerOneDestinationNames:
                $ref: "components/messages/inject/request/examples/dev/OneServerOneDestinationNames.yaml"
        required: true
      responses:
        "200":
          description: "OK"
        "500":
          description: "Internal Server Error"
  /api/v1/results/latency:
    post:
      tags:
        - Results
      description: >
        Provides the latency for a specific injection ID. This endpoint is used to measure the time taken for 
        messages to be processed
      summary: "GET results/v1/latency"
      operationId: "getLatencyForInjection"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LatencyRequestDto"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ResultResponseDto"
  /api/v1/results/{id}:
    get:
      summary: "GET results/v1/{id}"
      tags:
        - Results
      description: >
        This endpoint retrieves the result of the test run specified by the ID. The result includes the status of the test, 
        the number of messages processed, and any errors encountered during the test execution.
        
        If no test has been run yet, an empty result will be returned.
      operationId: getResult
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
          description: The unique identifier of the test run for which the result is being requested.
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ResultResponseDto"
              example:
                id: "68e6c2882ca40148849b67d8"
                loadProfileId: 5678
                elapsedTimeInSeconds: 850
        "404":
          description: NOT_FOUND
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "./components/common/schemas/Error.yaml"
                example:
                  - message: "No result found for id = 1"
  /api/v1/results:
    get:
      tags:
        - Results
      description: >
        Allows retrieval of all results for a given load profile ID.
      summary: "GET results/v1"
      operationId: "getResultsByLoadProfileId"
      parameters:
        - name: "loadProfileId"
          in: "query"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/ResultResponseDto"
  /api/v1/results/clear:
    post:
      tags:
        - Results
      description: >
        This endpoint clears all delivered messages from the system.
      summary: "POST results/v1/clear"
      operationId: "clearMessages"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ClearResponseDto"
  /api/v1/received:
    get:
      tags:
        - Received Messages
      summary: "GET api/v1/received"
      operationId: "getReceivedMessages"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ReceivedMessagesDto"
  /api/v1/load/profiles:
    get:
      summary: Get all LoadProfiles
      operationId: getLoadProfiles
      description:
        This endpoint is responsible for returning all LoadProfiles that have been created.
        
        A LoadProfile contains the criteria used to generate a load of messages. This criteria
        is added to the database when a load is generated. This allows users to see what criteria
        a specific message was generated with.
      tags:
        - Load Profiles
      responses:
        '200':
          $ref: components/load/profiles/responses/200/GetLoadProfile200Response.yaml
        '400':
          $ref: components/load/profiles/responses/400/GetLoadProfile400Response.yaml
        '404':
          $ref: components/load/profiles/responses/404/GetLoadProfile404Response.yaml
        '500':
          $ref: components/common/responses/500/500ErrorResponse.yaml
  /api/v1/load/profiles/{id}:
    get:
      summary: Get a LoadProfile by id
      operationId: getLoadProfile
      description:
        This endpoint is responsible for returning the LoadProfile details for a given id.

        A LoadProfile contains the criteria used to generate a load of messages. This criteria
        is added to the database when a load is generated. This allows users to see what criteria
        a specific message was generated with.
      tags:
        - Load Profiles
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          $ref: components/load/profiles/responses/200/GetLoadProfile200Response.yaml
        '400':
          $ref: components/load/profiles/responses/400/GetLoadProfile400Response.yaml
        '404':
          $ref: components/load/profiles/responses/404/GetLoadProfile404Response.yaml
        '500':
          $ref: components/common/responses/500/500ErrorResponse.yaml
    delete:
      tags:
        - Load Profiles
      summary: Delete a LoadProfile by id
      description:
        This endpoint is responsible for deleting the LoadProfile associated with a given id.
        
        A LoadProfile contains the criteria used to generate a load of messages. This criteria
        is added to the database when a load is generated. This allows users to see what criteria
        a specific message was generated with.
      operationId: deleteLoadProfile
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          $ref: components/load/profiles/responses/200/DeleteLoadProfile200Response.yaml
        '400':
          $ref: components/load/profiles/responses/400/DeleteLoadProfile400Response.yaml
        '404':
          $ref: components/load/profiles/responses/404/DeleteLoadProfile404Response.yaml
        '500':
          $ref: components/common/responses/500/500ErrorResponse.yaml
  /api/v1/load/messages/{id}:
    get:
      tags:
        - Generated Messages
      summary: Get a GeneratedMessage by id
      description:
        This endpoint is responsible for returning the individual generated message
        associated with the id provided.
      operationId: getGenerateMessage
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: components/load/messages/responses/200/GetGeneratedMessage200Response.yaml
        '400':
          $ref: components/load/messages/responses/400/GetGeneratedMessage400Response.yaml
        '404':
          $ref: components/load/messages/responses/404/GetGeneratedMessage404Response.yaml
        '500':
          $ref: components/common/responses/500/500ErrorResponse.yaml
    delete:
      tags:
        - Generated Messages
      summary: Delete a GeneratedMessage by id
      description:
        This endpoint is responsible for deleting the generated message
        associated with the id provided.
      operationId: deleteGeneratedMessage
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: components/load/messages/responses/200/DeleteGeneratedMessage200Response.yaml
        '404':
          $ref: components/load/messages/responses/404/DeleteGeneratedMessage404Response.yaml
        '500':
          $ref: components/common/responses/500/500ErrorResponse.yaml
  /api/v1/load/messages/profile/{id}:
    get:
      tags:
        - Generated Messages
      summary: Get all GeneratedMessages associated with a LoadProfile id
      description:
        Return the complete list of all messages that have been generated for a given LoadProfile.
      operationId: deleteGeneratedMessagesForProfile
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          $ref: components/load/messages/responses/200/GetGeneratedMessagesForProfile200Response.yaml
        '400':
          $ref: components/load/messages/responses/400/GetGeneratedMessagesForProfile400Response.yaml
        '404':
          $ref: components/load/messages/responses/404/GetGeneratedMessagesForProfile404Response.yaml
        '500':
          $ref: components/common/responses/500/500ErrorResponse.yaml
    delete:
      tags:
        - Generated Messages
      summary: Delete all GeneratedMessages associated with a LoadProfile id
      description:
        Delete all generated messages that are associated with the LoadProfile id provided.
      operationId: deleteGeneratedMessagesForProfile
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          $ref: components/load/messages/responses/200/DeleteGeneratedMessagesForProfile200Response.yaml
        '400':
          $ref: components/load/messages/responses/400/DeleteGeneratedMessagesForProfile400Response.yaml
        '404':
          $ref: components/load/messages/responses/404/DeleteGeneratedMessagesForProfile404Response.yaml
        '500':
          $ref: components/common/responses/500/500ErrorResponse.yaml
  /api/v1/configuration/servers:
    get:
      tags:
        - Configuration
      description: >
        This endpoint allows us to retrieve the server configurations for the IBM MQ servers.
      summary: "GET configuration/v1/servers"
      operationId: "getServer"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/GetServersResponseDto"
  /api/v1/event/send:
    $ref: paths/event/send/event-send.yaml

components:
  schemas:
    ReceivedMessageDto:
      type: "object"
      properties:
        id:
          type: "string"
          nullable: true
        handOffTimestamp:
          type: "integer"
          format: "int64"
          nullable: true
        protocol:
          type: "string"
          nullable: true
          enum:
            - "MATIP"
            - "IBMMQ"
        body:
          type: "string"
          nullable: true
        connectionName:
          type: "string"
          nullable: true
        queueName:
          type: "string"
          nullable: true
        injectionId:
          type: "string"
          nullable: true
    ReceivedMessagesDto:
      type: "object"
      properties:
        receivedMessages:
          type: "array"
          nullable: true
          items:
            $ref: "#/components/schemas/ReceivedMessageDto"
    LatencyRequestDto:
      type: "object"
      properties:
        injectionId:
          type: "string"
          nullable: true
        atMostInSeconds:
          type: "integer"
          format: "int32"
          nullable: true
          default: "20"
        pollDelayInSeconds:
          type: "integer"
          format: "int32"
          nullable: true
          default: "2"
        pollIntervalInSeconds:
          type: "integer"
          format: "int32"
          nullable: true
          default: "5"
    ResultResponseDto:
      type: "object"
      properties:
        id:
          type: "string"
        loadProfileId:
          type: "integer"
          format: "int64"
        elapsedTimeInSeconds:
          type: "integer"
          format: "int32"
    DestinationDetailsDto:
      type: "object"
      properties:
        server:
          type: "string"
          description: "The server address for the destination."
        port:
          type: "integer"
          format: "int32"
          description: "The port number for the destination server."
        destinationNames:
          type: "array"
          items:
            type: "string"
          description: "The queue names that messages will be sent to."
    SendMessageIbmMqRequestDto:
      type: "object"
      properties:
        destinationsDetailsList:
          type: "array"
          items:
            $ref: "#/components/schemas/DestinationDetailsDto"
          description: "Array of destination details where messages will be sent."
        loadProfileId:
          type: "integer"
          format: "int64"
          description: "Optional field to specify the load ID for the generated messages."
      example:
        destinationsDetailsList:
          - server: "localhost"
            port: 1414
            destinationNames:
              - "DEV.QUEUE.1"
        loadProfileId: 1
        preLoad: true
    GetServersResponseDto:
      type: "object"
      properties:
        serverConfigurations:
          type: "string"
    ClearResponseDto:
      type: "object"
      properties:
        numberOfMessagesCleared:
          type: "integer"
          format: "int32"